[package]
name = "integration-tests"
version = "0.1.0"
edition="2018"

[dependencies]
reool = { version="*", path=".." }
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"

[features]
basic_scheduler = []